name: digiteerth
description: A Spiritual Walking Journey App

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.2.2
  cupertino_icons: ^1.0.8

  # Maps
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2

  # Step Counter
  pedometer: ^4.1.1
  permission_handler: ^12.0.1

  # Local Storage
  shared_preferences: ^2.5.3

  # Audio
  just_audio: ^0.9.34

  # Video
  video_player: ^2.11.0

  # UI
  smooth_page_indicator: ^1.2.0

  # Utilities
  uuid: ^4.0.0
  intl: ^0.20.2
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_new.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/
    - assets/images/steps-backgrounds/
    - assets/images/stickers/
    - assets/images/hero-backgrounds/
    - assets/images/destination-backgrounds/