// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAesXEZBHR6tId-gxAyjwSPEaIV0fwVK6s',
    appId: '1:554660662027:web:a13b5fc1119c647b4ab00e',
    messagingSenderId: '554660662027',
    projectId: 'yatrawalk-abd84',
    authDomain: 'yatrawalk-abd84.firebaseapp.com',
    storageBucket: 'yatrawalk-abd84.firebasestorage.app',
    measurementId: 'G-151CW4WB6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR4CfAPvM34Qgz58ASHQ6nOoOX4GoWrts',
    appId: '1:554660662027:android:c4dfef13b805d2914ab00e',
    messagingSenderId: '554660662027',
    projectId: 'yatrawalk-abd84',
    storageBucket: 'yatrawalk-abd84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmPDpr7mebQTvtfnpvlvbTb3G-IsDyzuw',
    appId: '1:554660662027:ios:09302b5c28c959b04ab00e',
    messagingSenderId: '554660662027',
    projectId: 'yatrawalk-abd84',
    storageBucket: 'yatrawalk-abd84.firebasestorage.app',
    iosBundleId: 'com.example.yatrawalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmPDpr7mebQTvtfnpvlvbTb3G-IsDyzuw',
    appId: '1:554660662027:ios:09302b5c28c959b04ab00e',
    messagingSenderId: '554660662027',
    projectId: 'yatrawalk-abd84',
    storageBucket: 'yatrawalk-abd84.firebasestorage.app',
    iosBundleId: 'com.example.yatrawalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAesXEZBHR6tId-gxAyjwSPEaIV0fwVK6s',
    appId: '1:554660662027:web:fcaa3faa00563a214ab00e',
    messagingSenderId: '554660662027',
    projectId: 'yatrawalk-abd84',
    authDomain: 'yatrawalk-abd84.firebaseapp.com',
    storageBucket: 'yatrawalk-abd84.firebasestorage.app',
    measurementId: 'G-HC5YBJDVFX',
  );
}
